config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, shallow: true do
    resources :comments, only: [ :create, :destroy ], shallow: true do
      resources :comments, only: [ :create, :destroy ]
    end
    resources :likes, only: :create
  end

  resources :relationships, only: [ :index, :create ]
  get '/search', to: 'relationships#search', as: 'search'
  patch '/cancel/:id', to: 'relationships#cancel', as: 'cancel_relationship'
  patch '/accept/:id', to: 'relationships#accept', as: 'accept_relationship'
  patch '/decline/:id', to: 'relationships#decline', as: 'decline_relationship'
  get '/user/:username', to: 'users#show', as: 'user'

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end

  resources :chats, only: :index

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :chatrooms, only: [ :index, :show ] do
        resources :messages, only: :create
      end
    end
  end

  mount ActionCable.server => "/cable"

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  validates :note, presence: true, uniqueness: true

  # Help find post from child comments
  def self.find_post(ele)
    if ele.commentable_type == 'Post'
      Post.find(ele.commentable_id)
    else
      c = Comment.find(ele.commentable_id)
      find_post(c)
    end
  end

  # Method to count all child comments for a post
  def deep_count
    count = comments.count
    comments.each { |c| count += c.deep_count }
    count
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    authorize @comment
    if @comment.save
      unless @comment.commentable.user == current_user
        Notification.create(recipient: @comment.commentable.user, actor: current_user, action: "commented", notifiable: Comment.find_post(@comment))
      end
      @comment.commentable.comments.each { |comment| Notification.create(recipient: comment.user, actor: current_user, action: "commented", notifiable: Comment.find_post(@comment)) if comment.user != current_user}
      redirect_to post_path(Comment.find_post(@comment))
    else
      render template: "posts/show"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = Comment.find_post(@comment)
    @comment.destroy
    authorize @comment
    redirect_to post_path(post)
  end

  private

  def comment_params
    params.require(:comment).permit(:note)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
  end
end

app/views/comments/_comment.html.erb
<div class="row pl-5">
  <% if policy(comment).friends? %>
    <%= link_to user_path(comment.user.username), class: 'col-1' do %>
      <p><i><small> <%= comment.user.username %></small></i></p>
    <% end %>
  <% else %>
      <p class="col-1"><i><small>annonymous</small></i></p>
  <% end %>
  <p class="col-3"><i><small><%= comment.created_at.to_formatted_s(:long) %></small></i></p>
  <a data-toggle="collapse" href="#collapseReply<%= comment.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
    <i class="fas fa-reply"></i>
  </a>
  <p class="px-2">|</p>
  <% if policy(comment).destroy? %>
    <%= link_to comment_path(comment),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
    <% end %>
  <% end %>
</div>
<p class="pl-5"><%= comment.note %></p>

<div class="collapse px-3 py-3" id="collapseReply<%= comment.id %>">
  <div class="card card-body">
    <%= render 'comments/comment_form', comment: comment %>
  </div>
</div>
<hr>

<% comment.comments.each do |child_comment| %>
  <div class="replies pl-5">
    <%= render 'comments/comment', comment: child_comment, post: comment %>
  </div>
<% end %>

app/views/comments/_comment_form.html.erb
<%= simple_form_for [comment, Comment.new], html: { class: 'px-5 mx-3 pb-5' } do |f| %>
<%= f.input :note %>
<%= f.submit 'Reply', class: 'btn btn-outline-secondary' %>
<% end %>