config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, shallow: true do
    resources :comments, only: [ :create, :destroy ], shallow: true do
      resources :comments, only: [ :create, :destroy ]
    end
    resources :likes, only: :create
  end

  resources :relationships, only: [ :index, :create ]
  get '/search', to: 'relationships#search', as: 'search'
  patch '/cancel/:id', to: 'relationships#cancel', as: 'cancel_relationship'
  patch '/accept/:id', to: 'relationships#accept', as: 'accept_relationship'
  patch '/decline/:id', to: 'relationships#decline', as: 'decline_relationship'
  get '/user/:username', to: 'users#show', as: 'user'

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end

  resources :chats, only: :index

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :chatrooms, only: [ :index, :show ] do
        resources :messages, only: :create
      end
    end
  end

  mount ActionCable.server => "/cable"

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :find_friend_request, only: [:accept, :decline, :cancel]

  def index
    skip_policy_scope
    @friends = current_user.friends
    @pending_requests = current_user.friend_requests_as_requestor.where(status: "pending").flat_map(&:receiver)
    @pending_requests_received = current_user.friend_requests_as_receiver.where(status: "pending").flat_map(&:requestor)
  end

  def create
    friend = FriendRequest.new(requestor: current_user, receiver: User.find(params[:format]))
    authorize friend
    if friend.save
      Notification.create(recipient: friend.receiver, actor: friend.requestor, action: "submitted", notifiable: friend)
      redirect_to relationships_path
    else
      render :search
    end
  end

  def search
    @search_results = User.search_by_username(params[:search])
    @friend_request = FriendRequest.new
    authorize @friend_request
  end

  def accept
    @friend_request.status = "accepted"
    @friend_request.save
    friendship = Friendship.new(friend_a: @friend_request.requestor, friend_b: current_user)
    friendship.save
    Notification.create(recipient: @friend_request.opposed_user(current_user), actor: current_user, action: "accepted", notifiable: @friend_request)
    chatroom = Chatroom.create(sender: current_user, receiver: friendship.friend_a)
    Message.create(content: "Hi, let's be friends!", user: current_user, chatroom: chatroom)
    redirect_to relationships_path
  end

  def cancel
    @friend_request.destroy
    redirect_to relationships_path
  end

  def decline
    @friend_request.destroy
    redirect_to relationships_path
  end

  private

  def find_friend_request
    @friend_request = FriendRequest.find(params[:id])
    authorize @friend_request
  end
end

app/views/relationships/index.html.erb
<div class="container pt-5">
  <div class="main-container">
    <div class="row justify-content-between align-items-center">
      <h1 class="col-4 pt-3"><i class="fa fa-users" aria-hidden="true"></i> Friends</h1>
      <div class="offset-4 col-4 text-right">
        <%= form_tag(search_path, method: "get", class: "form-inline") do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Find friends" %>
            <%= submit_tag "Search", class: "ml-3 btn btn-outline-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
    <hr>
    <%= render 'shared/friends', friends: @friends, friend_search: false, pending_request: false, received: false %>
    <% if @pending_requests.present? %>
      <h1 class="pt-5">Pending Friend Requests</h1>
      <%= render 'shared/friends', friends: @pending_requests, friend_search: false, pending_request: true, received: false %>
    <% end %>
    <% if @pending_requests_received.present? %>
      <h1 class="pt-5">Pending Requests Received</h1>
      <%= render 'shared/friends', friends: @pending_requests_received, friend_search: false, pending_request: false, received: true %>
    <% end %>
  </div>
</div>

app/views/relationships/search.html.erb
<div class="container pt-5">
  <div class="main-container">
    <div class="row pb-3 align-items-center">
      <div class="col-8">
        <h1>Do you know them?</h1>
      </div>
      <div class="col-4 align-middle text-right">
        <%= form_tag(search_path, method: "get", class: "form-inline") do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Find friends" %>
            <%= submit_tag "Search", class: "ml-3 btn btn-outline-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
    <% if @search_results.present? %>
      <%= render 'shared/friends', friends: @search_results, friend_search: true, pending_request: false, received: false %>
    <% end %>
  </div>
</div>