config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, shallow: true do
    resources :comments, only: [ :create, :destroy ], shallow: true do
      resources :comments, only: [ :create, :destroy ]
    end
    resources :likes, only: :create
  end

  resources :relationships, only: [ :index, :create ]
  get '/search', to: 'relationships#search', as: 'search'
  patch '/cancel/:id', to: 'relationships#cancel', as: 'cancel_relationship'
  patch '/accept/:id', to: 'relationships#accept', as: 'accept_relationship'
  patch '/decline/:id', to: 'relationships#decline', as: 'decline_relationship'
  get '/user/:username', to: 'users#show', as: 'user'

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end

  resources :chats, only: :index

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :chatrooms, only: [ :index, :show ] do
        resources :messages, only: :create
      end
    end
  end

  mount ActionCable.server => "/cable"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Your Journal with <i class="fas fa-heart"> JupitersLB</i>
  </div>

  <div class="footer-links">

    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="https://github.com/JupitersLB" target="_blank"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>

  </div>
</div>

app/views/shared/_friends.html.erb
<div class="friend-cards">
  <% friends.each do |friend| %>
    <div class="friend-card shadow">
      <div class="friend-card-image">
        <% if friend.photo.attached? %>
          <%= cl_image_tag friend.photo.key, class: 'friend-image' %>
        <% else %>
          <%= image_tag "avatar.png", class: 'friend-image' %>
        <% end %>
      </div>
      <div class="friend-card-body">
        <%= link_to friend.username, user_path(friend.username) %>
      </div>
      <div class="friend-card-footer justify-content-between row">
        <div class="col text-center">
          <p><small><%= friend.posts.count %></small> <i class="fa fa-book" aria-hidden="true"></i></p>
        </div>
        <div class="col text-center">
          <p><small><%= friend.comments.count %></small> <i class="fa fa-comment" aria-hidden="true"></i></p>
        </div>
        <div class="col text-center">
          <p><small><%= friend.friends.count %></small> <i class="fa fa-users" aria-hidden="true"></i></p>
        </div>
      </div>
      <% if friend_search &&
            friend.friend_requests_as_receiver.where(requestor: current_user).first.nil? &&
            friend.friend_requests_as_requestor.where(receiver: current_user).first.nil? &&
            friend != current_user %>
        <div class="row friend-button justify-content-center">
          <%= link_to 'Add as Friend?', relationships_path(friend), method: :post, remote: true, class: 'col-8' %>
        </div>
      <% elsif pending_request %>
        <div class="row friend-button justify-content-center">
          <%= link_to 'Cancel', cancel_relationship_path(friend.friend_requests_as_receiver.first.id), method: :patch, remote: true, class: 'col-6' %>
        </div>
        <% elsif received %>
        <div class="row friend-buttons justify-content-center">
          <%= link_to 'Accept', accept_relationship_path(friend.friend_requests_as_requestor.first.id), method: :patch, class: 'col-5' %>
          <%= link_to 'Decline', decline_relationship_path(friend.friend_requests_as_requestor.first.id), method: :patch, remote: true, class: 'col-5 ml-2' %>
        </div>
      <% end %>
      <% if friend_search == true ||
             pending_request == true ||
             received == true
             %>
        <div class="overlay"></div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm fixed-top navbar-lewagon">
  <%= image_tag 'icon.jpg', height: 40 %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if user_signed_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Your Posts", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add an Entry", new_post_path, class: "nav-link"  %>
      </li>
    </ul>
  <% end %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item nav-link name-color">Hello, <%= current_user.username %></li>
      <li class="nav-item dropdown" data-behavior="notifications">
        <a class="nav-link" href="#" id="notificationDropdown" role="button" data-behavior="notifications-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-bell mr-3" data-behavior="notification-bell" aria-hidden="true"></i>
          <span data-behavior="unread-count"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="notificationDropdown" data-behavior="notification-items">
        </div>
      </li>
      <li class="nav-item dropdown">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My Page", user_path(current_user.username), class: "dropdown-item" %>
          <%= link_to "Friends", relationships_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    <% else %>
      <li class="nav-item">
        <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign in", user_session_path, class: "nav-link" %>
      </li>
    <% end %>
  </ul>
  </div>
</div>