config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, shallow: true do
    resources :comments, only: [ :create, :destroy ], shallow: true do
      resources :comments, only: [ :create, :destroy ]
    end
    resources :likes, only: :create
  end

  resources :relationships, only: [ :index, :create ]
  get '/search', to: 'relationships#search', as: 'search'
  patch '/cancel/:id', to: 'relationships#cancel', as: 'cancel_relationship'
  patch '/accept/:id', to: 'relationships#accept', as: 'accept_relationship'
  patch '/decline/:id', to: 'relationships#decline', as: 'decline_relationship'
  get '/user/:username', to: 'users#show', as: 'user'

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end

  resources :chats, only: :index

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :chatrooms, only: [ :index, :show ] do
        resources :messages, only: :create
      end
    end
  end

  mount ActionCable.server => "/cable"

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  validates :title, :content, presence: true, uniqueness: true

  # Method to count all child comments for a post
  def deep_count
    count = comments.count
    comments.each { |c| count += c.deep_count }
    count
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show destroy]

  def index
    @my_posts = policy_scope(Post).where(user: current_user).order(created_at: :desc).includes(:comments)
    ids = current_user.friends.pluck(:id) << current_user.id
    @all_posts = policy_scope(Post).where(user_id: ids).order(created_at: :desc)
  end

  def new
    @post = Post.new
    authorize @post
  end

  def show
    @comment = Comment.new
    authorize @comment
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.date = DateTime.now
    @post.user = current_user
    authorize @post
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    authorize @post
    redirect_to posts_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/views/posts/_comment_form.html.erb
<%= simple_form_for [@post, Comment.new] do |f| %>
<%= f.input :note %>
<%= f.submit 'Comment', class: 'btn btn-outline-secondary' %>
<% end %>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
<%= f.input :title %>
<%= f.input :content %>
<%= f.submit 'Publish', class: 'btn btn-outline-secondary' %>
<% end %>

app/views/posts/_posts.html.erb
<div class="accordion mb-3" id="accordionPosts">
  <% posts.each do |post| %>
    <div class="card" data-post-id="<%= post.id %>">
      <div class="card-header " id="heading<%= post.id %>">
        <div class="row">
          <div class="btn text-left col-10" type="button" data-toggle="collapse" data-target="#collapse<%= post.id %>" aria-expanded="true" aria-controls="collapse<%= post.id %>">
            <h3><%= post.title %></h3>
            <div class="emoji-tallies d-flex">
              <% if post.likes.count > 0 %>
                <% post.likes.map(&:value).uniq.each do |v| %>
                  <p><%= v.html_safe %></p>
                <% end %>
                <p class="pl-3" id="tally-count"><%= post.likes.count %></p>
              <% end %>
            </div>
          </div>
          <div class="col-2">
            <div class="row text-right">
              <%= link_to user_path(post.user.username), class: "col" do %>
                <p><small><%= post.user.username %></small></p>
              <% end %>
            </div>
            <div class="row text-right">
              <p class="col"><small> (<%= post.date.to_formatted_s(:short) %>)</small></p>
            </div>
          </div>
        </div>
      </div>

      <div id="collapse<%= post.id %>" class="collapse" aria-labelledby="heading<%= post.id %>" data-parent="#accordionPosts">
        <div class="card-body">
          <div class="row">
            <div class="col-11">
              <p><%= post.content %></p>
            </div>
            <% if policy(post).destroy? %>
              <div class="col-1 text-right">
                <%= link_to post_path(post),
                            method: :delete,
                            data: { confirm: "Are you sure?" } do %>
                            <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
              </div>
            <% end %>
          </div>

          <div class="row mt-3 justify-content-between">
            <div class="pl-3">
              <%= link_to post_path(post) do %>
                <p><i class="fa fa-comment" aria-hidden="true"></i> <small><%= post.deep_count %> comments</small> </p>
              <% end %>
            </div>
            <div class="emoji-likes d-flex align-middle mr-3">
              <div class="emoji-choices mr-3">
                <%= link_to post_likes_path(post, value: '&#128514'), method: :post, remote: true do %>
                  <p>&#128514</p>
                <% end %>
                <%= link_to post_likes_path(post, value: '&#x1F60D'), method: :post, remote: true do %>
                  <p>&#x1F60D</p>
                <% end %>
                <%= link_to post_likes_path(post, value: '&#x1F631'), method: :post, remote: true do %>
                  <p>&#x1F631</p>
                <% end %>
                <%= link_to post_likes_path(post, value: '&#x1F973'), method: :post, remote: true do %>
                  <p>&#x1F973</p>
                <% end %>
              </div>
              <div class="emoji-selector d-flex justify-content-center">
                <p>&#x1F642</p>
              </div>
            </div>

          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container py-5">
  <div class="my-container">

    <% if current_user.friends.count.zero? %>

      <%= render "posts/posts", posts: @my_posts %>

    <% else %>

      <ul class="nav nav-tabs pt-3" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="my-posts" data-toggle="tab" href="#posts" role="tab" aria-controls="home" aria-selected="true">Yours</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="all-posts" data-toggle="tab" href="#friends" role="tab" aria-controls="profile" aria-selected="false">Friends & You</a>
        </li>
      </ul>

      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
          <%= render "posts/posts", posts: @my_posts %>
        </div>
        <div class="tab-pane fade" id="friends" role="tabpanel" aria-labelledby="friends-tab">
          <%= render "posts/posts", posts: @all_posts %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container pt-5">
  <div class="main-container">
    <h3>What happened today?</h3>
    <%= render 'form' %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="container pt-5">
  <div class="my-container">
    <div class="post-card">
      <div class="post-card-header d-flex align-items-start">
        <h1 class ="col-10"><%= @post.title %></h1>
        <div class="col-2">
          <div class="row text-right">
            <%= link_to user_path(@post.user.username), class: 'col' do %>
              <p><small>By <%= @post.user.username %></small></p>
            <% end %>
          </div>
          <div class="row text-right">
            <p class="col"><small><%= @post.date.to_formatted_s(:long) %></small></p>
          </div>
        </div>
      </div>
      <div class="post-card-content py-3 pl-3">
        <p><%= @post.content %></p>
      </div>
      <div class="post-card-comments pl-3">
        <% @post.comments.each do |comment| %>
          <%= render 'comments/comment', comment: comment, post: @post %>
        <% end %>
      </div>
      <a class="btn btn-outline-secondary ml-3 my-3" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Add a comment
      </a>
      <div class="collapse px-3 py-3" id="collapseExample">
        <div class="card card-body">
          <%= render 'comment_form' %>
        </div>
      </div>
    </div>
  </div>
</div>